### ISSUE TITLE
Major refactor for initial release

### ISSUE THREAD

**Issue by jcallaham** [dynamicslab/hydrogym#56]
The current package structure was designed for not really designed for distribution or release.  We would like to be able to do a `pip install hydrogym` that does not depend on complicated installation configurations (PETSc, Firedrake, PyTorch, TF, etc).  The target for this would be similar to OpenAI gym, where the core dependencies are light but it provides an API for MuJoCo, etc.  Ideally the "core" modules would be enough to specify an interface for time-dependent PDE control that is compatible with the distributed training framework with Ray, but would still be solver- and discretization- agnostic.

The overall package will probably end up looking something like this:
```
hydrogym/
├── core.py
├── distributed/
    ├── ...
├── firedrake/
    ├── flow.py
    ├── ts.py
    ├── envs/
        ├── cavity.py
        ├── cylinder.py
        ├── pinball.py
        ├── step.py
    ├── utils/
        ├── io.py
        ├── linalg.py
        ├── utils.py
docker/
├── Dockerfile
docs/
├── ...
test/
├── ...
examples/
├── ...
setup.py
```

So possibly the whole thing could be installed with `pip install hydrogym[firedrake]`?  But I assume that would only likely be done in a Docker container...  @ludgerpaehler how far did you get with this on #53?  Also, I know we talked about this but I lost my notes... what should we be doing with Docker as part of this?  Should the new package be able to spin off Docker containers (using `docker-py` as part of the `FlowEnv`), or will the containers be handled by Ray?  Either way, it seems like we should probably maintain a `hydrogym-firedrake` image, right?

**Comment by jcallaham** [comment]
# TODO:

- [ ] Implement `ActuatorBase` (`DampedActuator`, etc)
- [ ] Implement `Controller(CallbackBase)`
- [ ] Update example scripts for new modeling/analysis layout
- [ ] Add resolvent analysis to modeling
- [ ] Test RL training with Ray (how does environment specification/registration work now?)
- [ ]

**Comment by jcallaham** [comment]
Have been testing RL training with Ray for the past week or so, but I keep having issues similar to #55 again, even with timestep 1e-3 (though apparently not if I use the spinningup implementation of PPO...?).

**Comment by jcallaham** [comment]
Confirmed that serial RL training is now working for the cylinder - still need to finish implementing the example configurations and a couple of other tweaks and I think it'll be ready to PR

**Comment by ludgerpaehler** [comment]
@jcallaham shall I look to quickly tie everything with the backend tomorrow s.t. we have a parallel training-ready version short of the general pip install and disentangling the user-level, and Firedrake below it?

**Comment by ludgerpaehler** [comment]
Looking at your refactor - I think how I could package everything up into a pip-installable package is like this:

Option 1: Just installing the core-API

```bash
pip install hydrogym
```

Option 2: Installing the core-API + Firedrake (inside of a virtualenv)

```bash
git clone git@github.com:dynamicslab/hydrogym.git && cd hydrogym
python setup.py build_ext --sim_engine=firedrake
```

where we can then naturally document the `sim_engine` interface s.t. the general framework is extensible and has longevity. Equally as much, this design will perform the separation/disaggregation between the reinforcement learning-level, and the simulation agents level to be able to use it across scales from Laptop to larger clusters..

@jcallaham what do you think of this installation structure?

**Comment by ludgerpaehler** [comment]
That way we could also easily add in e.g. [Phiflow](https://github.com/tum-pbs/PhiFlow) as a secondary backend later down the line. The author, @holl- showed interest in it here at NeurIPS

**Comment by ludgerpaehler** [comment]
@jcallaham
