### ISSUE TITLE
Add support for flow environments with body forces

### ISSUE THREAD

**Issue by jcallaham** [dynamicslab/hydrogym#84]
# Purpose

All of the current environments implement actuators as Dirichlet boundary conditions.  This makes sense physically, but many numerical flow control configurations implement actuation as a body force instead (for the cylinder wake in particular).  This has a few advantages, like not having feed-through effects from the actuation directly to the measurement and smoother estimates of the aerodynamic coefficients.

# TODO

- [ ] Add notes to documentation about the challenges with BC-based controls (especially for co-located control and measurement)
- [ ] Modify body force implementation so it doesn't assume that the body force is just noise (i.e. `eta` could be actuation)
- [ ] Add alternate paths for including BC-based and body force-based controls in timestepping.
- [ ] Add `BodyForceCylinder` implementation following Noack et al 2011.

**Comment by ludgerpaehler** [comment]
Environments with forces added using M-AIA and Nek5000.
